# Generated by Django 4.2.4 on 2023-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "starttime",
                    models.CharField(
                        blank=True, db_column="startTime", max_length=30, null=True
                    ),
                ),
                (
                    "endtime",
                    models.CharField(
                        blank=True, db_column="endTime", max_length=30, null=True
                    ),
                ),
                (
                    "hourworked",
                    models.IntegerField(blank=True, db_column="hourWorked", null=True),
                ),
                (
                    "rateperhour",
                    models.CharField(
                        blank=True, db_column="ratePerHour", max_length=30, null=True
                    ),
                ),
                (
                    "suppliername",
                    models.CharField(
                        blank=True, db_column="supplierName", max_length=100, null=True
                    ),
                ),
                (
                    "purchasenumber",
                    models.CharField(
                        blank=True,
                        db_column="purchaseNumber",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "purchase",
                "managed": False,
            },
        ),
    ]
